name: Run Code Checks

on:
  workflow_call:
    inputs:
      branch-name:
        required: false
        type: string

jobs:
  run-code-checks:
    name: Run Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        if: ${{ inputs.branch-name == '' }}
        uses: actions/checkout@v4

      - name: Checkout Code With Branch Name
        if: ${{ inputs.branch-name != '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}

      - name: Run Unit Tests
        run: make tests
